import { NextRequest, NextResponse } from "next/server";
import { requireRole } from "@/lib/rules/authRule";
import { validateBody, createUserSchema } from "@/lib/validations/schemas";
import { createServerSupabaseClient } from "@/lib/supabase/server";

export async function POST(request: NextRequest) {
  const { error: authErr, user } = await requireRole(request, "admin");
  if (authErr) return authErr;

  const { data, error: valErr } = await validateBody(request, createUserSchema);
  if (valErr) return valErr;

  const supabase = await createServerSupabaseClient();
  try {
    // 1. Insert User (Assume stack auth user creation handled separately or via triggers/admin api)
    const { data: newUser, error } = await supabase
      .from("users")
      .insert({
        name: data.name,
        email: data.email,
        role: data.role,
        is_active: true
        // If stack_auth_id is required, it must be generated by StackAuth first.
        // For MVP, we pass dummy or handle stack auth server side logic here.
      })
      .select()
      .single();

    if (error) throw error;

    // 2. If student, insert subscription
    if (data.role === "student" && data.plan_name) {
      await supabase.from("subscriptions").insert({
        user_id: newUser.id,
        plan_name: data.plan_name,
        start_date: data.start_date || new Date().toISOString(),
        end_date: data.end_date || new Date().toISOString(),
        status: "active"
      });
    }

    // 3. Audit log
    await supabase.from("audit_log").insert({
      table_name: "users",
      record_id: newUser.id,
      action: "INSERT",
      new_data: newUser,
      changed_by: user!.id
    });

    return NextResponse.json({ success: true, user: newUser });
  } catch (err) {
    console.error("[API Error] POST /admin/user", err);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
